//USER ACTIONS
export const SAVE_REGISTER_DATA = "SAVE_REGISTER_DATA";
export const LOGIN = "LOGIN";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const RECARGAR_DINERO = "RECARGAR_DINERO";
export const EMPTY_REDUX = "EMPTY_REDUX";
